puts "Hello World!"
puts "Hello Again"
puts "I like typing this."
puts "This is fun."
puts "Yay! Printing."
puts "I'd much rather you 'not' . "
puts 'I "said" do not touch this.'
puts " "
puts "Study Drill Prompt 1"
puts " "
puts "This is another line."
puts "we Capitalize some things To see if you're detail oriented."
puts "sometimes we use the 'carot' to trick you"
puts "if you forgot to hit 'save' in Atom your program will not run"
puts "Your coffee is going to be too strong if you don't take a break and drink it"
puts " "
puts "Study Drill Prompt 2"
puts #{}"This is another line."
puts "we Capitalize some things To see if you're detail oriented."
puts #{}"sometimes we use the 'carot' to trick you"
puts #{}"if you forgot to hit 'save' in Atom your program will not run"
puts #{}"Your coffee is going to be too strong if you don't take a break and drink it"
puts " "
puts "Study Drill Prompt 3"
puts "Octothorpes prevent a line of code from running"
puts "While im not sure 'how' exactly, I do know they are hard to spell"
